spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8a092f5664.goho.co:23490/cjh?serverTimeZone=UTC
    username: root
    password: 123456
  # session失效时间
  session:
    timeout: 86400
